# Generated by Django 2.1.7 on 2019-03-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('te_id', models.CharField(max_length=256, verbose_name='固定资产主键')),
                ('te_class', models.CharField(max_length=32, verbose_name='资产类别')),
                ('te_local', models.CharField(max_length=16, verbose_name='校区位置')),
                ('te_build', models.CharField(max_length=16, verbose_name='实验楼')),
                ('te_floor', models.CharField(max_length=4, verbose_name='楼层')),
                ('te_room', models.CharField(max_length=5, verbose_name='房间')),
                ('te_Xdata', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='X轴数据')),
                ('te_Ydata', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Y轴数据')),
                ('te_Zdata', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Z轴数据')),
                ('te_ladata', models.DateField(verbose_name='上次清查日期')),
                ('te_nedata', models.DateField(verbose_name='下次清查日期')),
                ('te_buydate', models.DateField(verbose_name='购买日期')),
                ('te_make', models.CharField(max_length=256, verbose_name='设备生产商')),
                ('te_persion', models.CharField(max_length=32, verbose_name='设备负责人')),
                ('te_status', models.BooleanField(verbose_name='设备能否正常使用')),
                ('te_back', models.TextField(verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_id', models.CharField(max_length=1024, verbose_name='药品主键')),
                ('ph_name', models.CharField(max_length=512, verbose_name='药品名称')),
                ('ph_class', models.CharField(max_length=256, verbose_name='药品类别')),
                ('ph_status', models.CharField(max_length=128, verbose_name='药品状况')),
                ('ph_indata', models.DateField(verbose_name='入库时间')),
                ('ph_outdata', models.DateField(verbose_name='过期时间')),
                ('ph_enddata', models.DateField(verbose_name='使用结束时间')),
            ],
        ),
    ]
