# Generated by Django 2.1.7 on 2019-03-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localtion', '0003_auto_20190308_0917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pharmacy',
        ),
    ]
