# Generated by Django 3.1.2 on 2020-10-21 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WhereStand', models.SmallIntegerField(choices=[(0, '奉贤校区'), (1, '徐汇校区'), (2, '金山校区')], default=0, verbose_name='校区')),
                ('HouseNumber', models.IntegerField(default=1, verbose_name='实验楼号')),
            ],
            options={
                'verbose_name': '校区+实验楼',
                'verbose_name_plural': '校区',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='厂商名称')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='电话')),
            ],
            options={
                'verbose_name': '厂商',
                'verbose_name_plural': '厂商',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomNum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '房间号',
                'verbose_name_plural': '房间号',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': '用户基本信息',
                'verbose_name_plural': '用户基本信息',
            },
        ),
        migrations.CreateModel(
            name='AsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='编号')),
                ('called', models.CharField(blank=True, max_length=64, null=True, verbose_name='名称')),
                ('status', models.SmallIntegerField(choices=[(0, '正常未使用'), (1, '故障'), (2, '备用'), (3, '未知'), (4, '使用中')], default=0, verbose_name='状态')),
                ('indate', models.DateField(blank=True, null=True, verbose_name='入库日期')),
                ('expiredate', models.DateField(blank=True, null=True, verbose_name='过期时间')),
                ('manageIP', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('x_locations', models.CharField(blank=True, max_length=254, null=True, verbose_name='定位信息X')),
                ('y_locations', models.CharField(blank=True, max_length=254, null=True, verbose_name='定位信息Y')),
                ('z_locations', models.CharField(blank=True, max_length=254, null=True, verbose_name='定位信息Z')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.house', verbose_name='实验楼')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aadmin', to='CMDB.user', verbose_name='管理者')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.manufacturer', verbose_name='制造商')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMDB.room', verbose_name='房间号')),
            ],
            options={
                'verbose_name': '资产总表',
                'verbose_name_plural': '总表',
                'ordering': ['-sn'],
            },
        ),
    ]
