# Generated by Django 2.1.7 on 2019-03-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_id', models.CharField(max_length=1024, verbose_name='药品编码')),
                ('ph_name', models.CharField(max_length=512, verbose_name='药品名称')),
                ('ph_class', models.CharField(max_length=256, verbose_name='药品类别')),
                ('ph_status', models.CharField(max_length=128, verbose_name='药品状况')),
                ('ph_indata', models.DateField(verbose_name='入库时间')),
                ('ph_outdata', models.DateField(verbose_name='过期时间')),
                ('ph_enddata', models.DateField(verbose_name='使用结束时间')),
            ],
        ),
    ]
